services:
  backend:
    image: kablux_backend:latest
    container_name: "artflght_backend"
    restart: always
    build: .
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    ports:
      - 8000
    env_file:
      - .env

  db:
    image: postgres:alpine3.20
    container_name: "artflght_postgres"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    restart: always
      
volumes:
  static_volume:
  postgres_data: