# Generated by Django 5.2.1 on 2025-10-15 11:56

import core.models
import drf_starter.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artimage',
            name='image',
            field=models.ImageField(storage=drf_starter.storage_backends.PublicMediaStorage(), upload_to='art_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=drf_starter.storage_backends.PublicMediaStorage(), upload_to=core.models.upload_to),
        ),
    ]
