# Generated by Django 5.2.1 on 2025-10-27 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogcategory_user_city_user_country_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='artimage',
            name='category',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Installation', 'Installation'), ('Digital Art', 'Digital Art'), ('AI Art', 'AI Art'), ('Sculpture', 'Sculpture'), ('Printmaking', 'Printmaking'), ('Explorative Art', 'Explorative Art'), ('Ceramics', 'Ceramics'), ('Drawing', 'Drawing'), ('Photograph', 'Photograph')], default='Painting', max_length=50),
        ),
        migrations.CreateModel(
            name='ArtFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='artimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.artfolder'),
        ),
    ]
