# Generated by Django 5.2.1 on 2025-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artimage_options_artimage_category_artfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
