# Generated by Django 5.2.1 on 2025-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artimage',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artimage',
            name='year_created',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
