# Generated by Django 5.2.1 on 2025-11-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
