# Generated by Django 5.2.1 on 2025-11-11 11:19

import drf_starter.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_artimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=drf_starter.storage_backends.PublicMediaStorage(), upload_to='blog_cover/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
